### ISSUE TITLE
谢谢，有编目和编目及文档细粒度权限管理吗？

### ISSUE THREAD

**Issue by defineconst** [yupaits/docs-manage#5]
您好，是否有
1、编目管理
2、编目权限
3、文档预览
4、文档权限等功能
谢谢！

**Comment by yupaits** [comment]
这个项目的重点是认证授权这块，所以对于文档的编目、权限管理等功能几乎是没有投入的；这个库早期的版本有一些功能可以借鉴。
如果你有兴趣可以提交PR :smiley:

**Comment by defineconst** [comment]
谢谢回复。
以前弄文档管理就是数据库建一个id、pid的编目表，然后关联文档和属性，但这样有个问题编目节点多，意味着该表非常大，遍历慢，同时在内部共享文档涉及到编目和文档权限，如何授权鉴权也有个效率文档。类似hadoop就用文件目录方式管理，对于一个没有运维和IT的公司，系统交付后技术支持成本也高，不知道您有没有遇到这样的问题。

**Comment by yupaits** [comment]
单表数据量大可以尝试分表；按文件目录方式授权我个人觉得不太灵活而且不利于拓展，授权的技术支持成本高，我个人觉得是缺乏一个高效的、人性化的授权交互界面。
具体关于文档管理的专业知识了解的不多，仅供参考。
